<#
.SYNOPSIS
    从 source/raw.txt 生成去重、排序后的域名集产物。

.DESCRIPTION
    读取原始域名列表，做清洗（去空白 / 去注释 / 去协议前缀 / 去端口与路径 / 转小写）、
    去重，并按 ASCII 字典序（ordinal）排序，然后生成：

      domains.txt     纯域名列表，每行一个
      clash.yaml      Mihomo / Clash rule-provider（behavior: domain）
      singbox.json    sing-box rule-set

    默认产出「域名 + 其子域名」的匹配语义：Clash 侧给每条加 "+." 前缀，
    sing-box 侧使用 domain_suffix。若要严格精确匹配，加 -Exact。

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\build.ps1

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\build.ps1 -Exact
#>
[CmdletBinding()]
param(
    # 原始列表路径，默认 <repo>/source/raw.txt
    [string]$Source,

    # 产物输出目录，默认仓库根目录
    [string]$OutDir,

    # 严格精确匹配（Clash 不加 "+." 前缀，sing-box 用 domain 而非 domain_suffix）
    [switch]$Exact
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
if (-not $Source) { $Source = Join-Path $root 'source\raw.txt' }
if (-not $OutDir) { $OutDir = $root }

if (-not (Test-Path -LiteralPath $Source)) {
    throw "找不到原始列表文件: $Source"
}
if (-not (Test-Path -LiteralPath $OutDir)) {
    New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
}

# ---------- 读取 + 清洗 + 去重（SortedSet 同时保证唯一与 ordinal 有序） ----------
$raw = [System.IO.File]::ReadAllLines($Source, [System.Text.Encoding]::UTF8)

$unique = New-Object 'System.Collections.Generic.SortedSet[string]' ([System.StringComparer]::Ordinal)
$total  = 0

foreach ($line in $raw) {
    $d = $line.Trim()
    if ($d.Length -eq 0) { continue }
    if ($d[0] -eq '#')   { continue }          # 注释行

    $d = $d -replace '^[a-zA-Z][a-zA-Z0-9+.\-]*://', ''   # 去掉 http:// 等协议前缀
    $d = $d -replace '[:/?#].*$', ''                       # 去掉端口 / 路径 / 查询串
    $d = $d.Trim().TrimEnd('.').Trim()
    if ($d.Length -eq 0) { continue }

    $d = $d.ToLowerInvariant()
    $total++
    [void]$unique.Add($d)
}

$domains = [string[]]@($unique)
$removed = $total - $domains.Count

# ---------- 写出 ----------
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Lines([string]$Path, [string[]]$Lines) {
    [System.IO.File]::WriteAllText($Path, (($Lines -join "`n") + "`n"), $utf8NoBom)
}

$pDomains = Join-Path $OutDir 'domains.txt'
$pClash   = Join-Path $OutDir 'clash.yaml'
$pSingbox = Join-Path $OutDir 'singbox.json'

# 1) domains.txt —— 纯列表，无注释无空行，可直接被任意客户端按行引用
Write-Lines $pDomains $domains

# 2) clash.yaml —— rule-provider，behavior: domain
$clashPrefix = if ($Exact) { '' } else { '+.' }
$clash = New-Object System.Collections.Generic.List[string]
$clash.Add('# pt-domains - Mihomo / Clash rule-provider (behavior: domain)')
$clash.Add('# Generated by tools/build.ps1 - DO NOT EDIT. Edit source/raw.txt instead.')
$clash.Add('payload:')
foreach ($d in $domains) { $clash.Add("  - '$clashPrefix$d'") }
Write-Lines $pClash $clash.ToArray()

# 3) singbox.json —— rule-set，version 2
$key = if ($Exact) { 'domain' } else { 'domain_suffix' }
$inner = New-Object System.Collections.Specialized.OrderedDictionary
$inner.Add($key, $domains)
$rule = New-Object System.Collections.Specialized.OrderedDictionary
$rule.Add('rules', @($inner))
$set = New-Object System.Collections.Specialized.OrderedDictionary
$set.Add('version', 2)
foreach ($k in $rule.Keys) { $set.Add($k, $rule[$k]) }

$json = $set | ConvertTo-Json -Depth 10
[System.IO.File]::WriteAllText($pSingbox, ($json -replace "`r`n", "`n") + "`n", $utf8NoBom)

# ---------- 汇总 ----------
Write-Host ''
Write-Host ("source  : " + $Source)
Write-Host ("output  : " + $OutDir)
Write-Host ("mode    : " + $(if ($Exact) { 'exact' } else { 'domain + subdomains' }))
Write-Host ("domains : " + $domains.Count + " unique (" + $removed + " duplicates removed)")
Write-Host ("written : " + [System.IO.Path]::GetFileName($pDomains) + " / " + [System.IO.Path]::GetFileName($pClash) + " / " + [System.IO.Path]::GetFileName($pSingbox))
Write-Host ''
