<#
.SYNOPSIS
    归一化域名清单，并生成配套的规则产物。

.DESCRIPTION
    domains.txt 是唯一的维护入口。直接编辑它即可：加一行就是新增域名，
    删一行就是删掉失效域名；顺序随意、重复随意、大小写随意。

    本脚本先把 domains.txt 归一化后原地写回：
      去空行 / 跳过 "#" 注释 / 去掉 http:// 等协议前缀 / 去掉端口与路径与查询串 /
      去掉开头的 "+." 与 "*." 通配前缀 / 去掉结尾的点 / 统一小写 / 去重 /
      按 ASCII 字典序（ordinal）排序

    然后同步生成：
      clash.yaml        Mihomo / Clash rule-provider（behavior: domain）
      singbox.json      sing-box rule-set
      pt-domains.list   DOMAIN-SUFFIX 纯文本规则列表（软路由 / classical 格式）

    默认产出「域名 + 其子域名」语义：Clash 侧给每条加 "+." 前缀，
    sing-box 侧使用 domain_suffix，.list 侧使用 DOMAIN-SUFFIX。
    加 -Exact 可改为严格精确匹配。

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\build.ps1

.EXAMPLE
    powershell -NoProfile -ExecutionPolicy Bypass -File tools\build.ps1 -Exact
#>
[CmdletBinding()]
param(
    # 域名清单路径，默认 <repo>/domains.txt
    [string]$Source,

    # 严格精确匹配（Clash 不加 "+." 前缀，sing-box 用 domain 而非 domain_suffix）
    [switch]$Exact
)

$ErrorActionPreference = 'Stop'

$root = Split-Path -Parent $PSScriptRoot
if (-not $Source) { $Source = Join-Path $root 'domains.txt' }
$Source = [System.IO.Path]::GetFullPath($Source)

if (-not (Test-Path -LiteralPath $Source)) {
    throw "domain list not found: $Source"
}
$OutDir = Split-Path -Parent $Source

# ---------- 读取 + 清洗 + 去重（SortedSet 同时保证唯一与 ordinal 有序） ----------
$raw = [System.IO.File]::ReadAllLines($Source, [System.Text.Encoding]::UTF8)

$unique = New-Object 'System.Collections.Generic.SortedSet[string]' ([System.StringComparer]::Ordinal)
$total  = 0

foreach ($line in $raw) {
    $d = $line.Trim()
    if ($d.Length -eq 0) { continue }
    if ($d[0] -eq '#')   { continue }                    # 注释行

    $d = $d -replace '^[a-zA-Z][a-zA-Z0-9+.\-]*://', ''  # 去掉 http:// 等协议前缀
    $d = $d -replace '[:/?#].*$', ''                     # 去掉端口 / 路径 / 查询串
    $d = $d -replace '^\+\.', ''                         # 去掉开头的 "+." 通配前缀
    $d = $d -replace '^\*\.', ''                         # 去掉开头的 "*." 通配前缀
    $d = $d.Trim().TrimStart('.').TrimEnd('.').Trim()    # 去掉首尾的点与空白
    if ($d.Length -eq 0) { continue }

    $d = $d.ToLowerInvariant()
    $total++
    [void]$unique.Add($d)
}

$domains = [string[]]@($unique)
if ($domains.Count -eq 0) { throw "domain list is empty: $Source" }
$dupes = $total - $domains.Count

# ---------- 写出 ----------
$utf8NoBom = New-Object System.Text.UTF8Encoding($false)

function Write-Lines([string]$Path, [string[]]$Lines) {
    [System.IO.File]::WriteAllText($Path, (($Lines -join "`n") + "`n"), $utf8NoBom)
}

$pDomains = $Source
$pClash   = Join-Path $OutDir 'clash.yaml'
$pSingbox = Join-Path $OutDir 'singbox.json'
$pList    = Join-Path $OutDir 'pt-domains.list'

# 1) domains.txt —— 纯列表，无注释无空行，既是清单也是可直接按行引用的产物
Write-Lines $pDomains $domains

# 2) clash.yaml —— rule-provider，behavior: domain
$clashPrefix = if ($Exact) { '' } else { '+.' }
$clash = New-Object System.Collections.Generic.List[string]
$clash.Add('# pt-domains - Mihomo / Clash rule-provider (behavior: domain)')
$clash.Add('# Generated by tools/build.ps1 - DO NOT EDIT. Edit domains.txt instead.')
$clash.Add('payload:')
foreach ($d in $domains) { $clash.Add("  - '$clashPrefix$d'") }
Write-Lines $pClash $clash.ToArray()

# 3) singbox.json —— rule-set，version 2
# 手工拼接而非 ConvertTo-Json：后者的缩进/转义在不同 PowerShell 版本间不一致，
# 会导致本地（5.1）与 GitHub Actions（pwsh 7）生成的文件反复互相覆盖。
$key = if ($Exact) { 'domain' } else { 'domain_suffix' }
$sb = New-Object System.Text.StringBuilder
[void]$sb.Append("{`n")
[void]$sb.Append("  `"version`": 2,`n")
[void]$sb.Append("  `"rules`": [`n")
[void]$sb.Append("    {`n")
[void]$sb.Append("      `"$key`": [`n")
for ($i = 0; $i -lt $domains.Count; $i++) {
    $tail = if ($i -lt ($domains.Count - 1)) { ',' } else { '' }
    [void]$sb.Append("        `"$($domains[$i])`"$tail`n")
}
[void]$sb.Append("      ]`n")
[void]$sb.Append("    }`n")
[void]$sb.Append("  ]`n")
[void]$sb.Append("}")
[System.IO.File]::WriteAllText($pSingbox, $sb.ToString() + "`n", $utf8NoBom)

# 4) pt-domains.list —— DOMAIN-SUFFIX 纯文本规则列表
# 不带 -Exact 时用 DOMAIN-SUFFIX（域名及其所有子域名都命中），
# 带 -Exact 时用 DOMAIN（只命中列出的域名本身）。
$listRule = if ($Exact) { 'DOMAIN' } else { 'DOMAIN-SUFFIX' }
$list = New-Object System.Collections.Generic.List[string]
foreach ($d in $domains) { $list.Add("$listRule,$d") }
Write-Lines $pList $list.ToArray()

# ---------- 汇总 ----------
Write-Host ''
Write-Host ("list    : " + $pDomains)
Write-Host ("mode    : " + $(if ($Exact) { 'exact' } else { 'domain + subdomains' }))
Write-Host ("domains : " + $domains.Count + " unique (" + $dupes + " duplicates removed)")
Write-Host ("written : domains.txt / clash.yaml / singbox.json / pt-domains.list")
Write-Host ''
